### ISSUE TITLE
недостающие предметы

### ISSUE THREAD

**Issue by ev-br** [ev-br/gia#2]
Относительно вопросника 2017/18 года:

- [x] Уравнения математической физики
- [x] 6.2. Теория вероятностей и математическая статистика
- [x] 6.3. Методы оптимизации --- *П.В. обновляет*
- [x] 6.4. Дискретная математика (математическая логика, теория графов, теория алгоритмов)
- [x] 6.5. Случайные процессы и теория массового обслуживания
- [x] 6.6. Численные методы --- <s>*E.Б. обновляет*</s>
- [x] 6.7. Операционные системы
- [x] 6.8. Дифференциальные уравнения
- [x] 6.9. Математический анализ
- [x] 6.10. Линейная алгебра и геометрия
- [x] 6.11. Программирование
- [x] 6.13. Теория управления

**Comment by ev-br** [comment]
- [ ] Уравнения математической физики
- [ ] 6.2. Теория вероятностей и математическая статистика
- [ ] 6.3. Методы оптимизации
- [ ] 6.4. Дискретная математика (математическая логика, теория графов, теория алгоритмов)
- [ ] 6.5. Случайные процессы и теория массового обслуживания
- [ ] 6.6. Численные методы
- [ ] 6.7. Операционные системы
- [ ] 6.8. Дифференциальные уравнения
- [ ] 6.9. Математический анализ
- [ ] 6.10. Линейная алгебра и геометрия
- [ ] 6.11. Программирование
- [ ] 6.13. Теория управления

**Comment by ev-br** [comment]
@pixelmagenta текущее состояние. Понятно, кому нужно напомнить.

**Comment by pixelmagenta** [comment]
Юрий Юрьевич не отвечает по известным нам каналам связи (почта, мобильный телефон, домашний телефон). Попробуем в понедельник лично попросить.
За теорию вероятностей и математическую статистику Юлия Борисовна ответственна или я ошибаюсь?

**Comment by ev-br** [comment]
По обоим пунктам "да".
