### ISSUE TITLE
Изменить вопросы по ТФКП 

### ISSUE THREAD

**Issue by nbagiyan** [ev-br/gia#8]
Во вторник, Павел Алексеевич вместе с нами еще раз упростил вопросник. Сейчас в репозитории, к сожалению, неактуальная версия. Новую версию прикрепил к issue.

![image](https://user-images.githubusercontent.com/17412060/56421340-b4df3480-62aa-11e9-8b91-5be8cac3588e.png)

**Comment by ev-br** [comment]
Closed by gh-9
